import type { TaskTemplate } from '@/types'

export const TASK_TEMPLATES: TaskTemplate[] = [
  {
    id: 'zaladuj-zmywarke',
    title: 'Załaduj zmywarkę',
    description: 'Ułóż naczynia w zmywarce i dodaj kapsułkę.',
    emoji: '🍽️',
    default_coins: 30,
    default_difficulty: 'easy',
    suggested_checklist: [
      'Zebrać naczynia ze zlewu i stołu',
      'Poustawiać talerze, kubki, sztućce',
      'Dodać kapsułkę do zmywarki',
      'Ustawić program i uruchomić',
    ],
    room: 'kuchnia',
  },
  {
    id: 'rozladuj-zmywarke',
    title: 'Rozładuj zmywarkę',
    description: 'Wyjmij czyste naczynia i odłóż na miejsce.',
    emoji: '🥣',
    default_coins: 25,
    default_difficulty: 'easy',
    suggested_checklist: [
      'Sprawdzić czy naczynia są czyste i suche',
      'Odłożyć talerze do szafki',
      'Odłożyć kubki i szklanki',
      'Odłożyć sztućce do szuflady',
      'Zamknąć zmywarkę',
    ],
    room: 'kuchnia',
  },
  {
    id: 'rozwiesic-pranie',
    title: 'Rozwiesić pranie',
    description: 'Wyjmij pranie z pralki i rozwieś na suszarce.',
    emoji: '👕',
    default_coins: 60,
    default_difficulty: 'medium',
    suggested_checklist: [
      'Wyjąć pranie z pralki',
      'Roztrząsnąć każdą sztukę',
      'Rozwieszić na suszarce (zostawić miejsce na cyrkulację)',
      'Sprawdzić czy nic się nie zgniata',
    ],
    room: 'prania',
  },
  {
    id: 'rozbrac-suche-pranie',
    title: 'Rozebrać suche pranie do szafek',
    description: 'Złóż wysuszone pranie i odłóż do odpowiednich szafek.',
    emoji: '👗',
    default_coins: 50,
    default_difficulty: 'medium',
    suggested_checklist: [
      'Sprawdzić czy pranie jest suche',
      'Złożyć każdą sztukę',
      'Odłożyć do właściwych szafek i szuflad',
      'Złożyć suszarkę lub przestawić',
    ],
    room: 'prania',
  },
  {
    id: 'odkurzyc-salon',
    title: 'Odkurzyć salon',
    description: 'Odkurzyć całą podłogę w salonie, łącznie z przestrzenią pod meblami.',
    emoji: '🧹',
    default_coins: 50,
    default_difficulty: 'medium',
    suggested_checklist: [
      'Przesunąć poduszki i małe przedmioty',
      'Odkurzyć środek pokoju',
      'Odkurzyć pod kanapą i przy meblach',
      'Odkurzyć przy ścianach',
      'Odstawić odkurzacz na miejsce',
    ],
    room: 'salon',
  },
  {
    id: 'lazienka-taty',
    title: 'Wyczyścić łazienkę Taty',
    description: 'Łazienka Taty z kabiną prysznicową — umywalka, sedes, prysznic, podłoga.',
    emoji: '🚿',
    default_coins: 70,
    default_difficulty: 'hard',
    suggested_checklist: [
      'Wyczyścić kabinę prysznicową (szyby i brodzik)',
      'Wyczyścić umywalkę',
      'Wyczyścić sedes (zewnątrz i wewnątrz)',
      'Umyć podłogę',
      'Wytrzeć lustro',
      'Wymienić ręcznik jeśli potrzeba',
    ],
    room: 'lazienka_taty',
  },
  {
    id: 'lazienka-z-wanna',
    title: 'Wyczyścić łazienkę z wanną',
    description: 'Łazienka dziewczyn i Mamy — wanna, umywalka, sedes, podłoga.',
    emoji: '🛁',
    default_coins: 80,
    default_difficulty: 'hard',
    suggested_checklist: [
      'Wyszorować wannę (środek i zewnątrz)',
      'Wyczyścić umywalkę',
      'Wyczyścić sedes (zewnątrz i wewnątrz)',
      'Umyć podłogę',
      'Wytrzeć lustro',
      'Wymienić ręczniki jeśli potrzeba',
    ],
    room: 'lazienka_dziewczyn',
  },
  {
    id: 'korytarz',
    title: 'Pozbierać rzeczy w korytarzu',
    description: 'Pozbierać i odłożyć na miejsce wszystkie rzeczy leżące w korytarzu.',
    emoji: '📦',
    default_coins: 20,
    default_difficulty: 'easy',
    suggested_checklist: [
      'Odłożyć buty do szafki lub na miejsce',
      'Powiesić kurtki i torby',
      'Wynieść rzeczy do innych pokoi',
      'Sprawdzić czy podłoga jest wolna',
    ],
    room: 'korytarz',
  },
  {
    id: 'pokoj-hania-maria',
    title: 'Posprzątać pokój (Hania & Maria)',
    description: 'Posprzątać pokój Hani i Marii — odłożyć rzeczy, pościelić łóżka.',
    emoji: '🛏️',
    default_coins: 40,
    default_difficulty: 'medium',
    suggested_checklist: [
      'Pościelić oba łóżka',
      'Pozbierać ubrania z podłogi',
      'Odłożyć książki i rzeczy na miejsce',
      'Przetrzeć biurko',
    ],
    room: 'pokoj_hania_maria',
  },
  {
    id: 'pokoj-sonia',
    title: 'Posprzątać pokój Soni',
    description: 'Posprzątać pokój Soni — odłożyć rzeczy, pościelić łóżko.',
    emoji: '🛏️',
    default_coins: 40,
    default_difficulty: 'medium',
    suggested_checklist: [
      'Pościelić łóżko',
      'Pozbierać ubrania z podłogi',
      'Odłożyć rzeczy na miejsce',
      'Przetrzeć biurko',
    ],
    room: 'pokoj_sonia',
  },
]
